name: "Terraform CI for AWS-EC2"
on: 
    push:
        branches: 
            - main
    paths:
      - terraform-ec2-auto/**

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: us-east-1

jobs:
  terraform:
    -name: "Terraform Plan and Apply"
    runs-on: ubuntu-latest
    defaults:
        runs:
          shell: bash
          working-directory: ./terraform-ec2-auto    
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v1

        - name: Terraform Init
          run: terraform init

        - name: Terraform Validate
          run: terraform validate

        - name: Terraform Plan
          run: terraform plan -out=tfplan

        - name: Terraform Apply
          if: github.event_name == 'push'        
          run: terraform apply -auto-approve tfplan